name: EduTrace_Api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image from subdirectory
      run: docker build EduTrace_Api --file EduTrace_Api/Dockerfile --tag my-image-name:$(date +%s)
